### ISSUE TITLE
Compile with Java 7

### ISSUE THREAD

**Issue by estenwig** [acanda/spring-banner-plugin#1]
I surgest you rewrite this plugin to use Java 7 as it can not be used on projects compiled with Java version less than java 8.
Optionaly av Java8  as a prerequisit in the pom file.

**Comment by acanda** [comment]
Java 7 reached end of life over a year ago. The maven plugin uses both the Java 8 API and language features extensively. Supporting Java 7 is therefore out of the question.

If your Spring application requires Java 7 you can still use this plugin though. You just have to run Maven with Java 8. If you have configured your POM correctly then it will still produce Java 7 class files.
