### ISSUE TITLE
Banner not displaying variables

### ISSUE THREAD

**Issue by peterkronenberg** [acanda/spring-banner-plugin#18]
Hi, I'm using the exmaple from the readme, but the only values that is displayed is the port

Here is my configuration from the pom:
```
              <configuration> <!--(2)-->
                    <text>${project.name}</text>
<!--                    <outputDirectory>${project.build.outputDirectory}</outputDirectory>-->
                    <outputDirectory>src/main/resources</outputDirectory>
                    <filename>banner.txt</filename>
                    <includeInfo>true</includeInfo>
                    <info>Version: ${application.version}, Server: ${server.address}:${server.port}, Active Profiles: ${spring.active.profiles}
                    </info>
<!--                    <version>${project.version}</version>-->
                    <font>standard</font>
                    <color>default</color>
                </configuration>
```

and here is the output I'm getting

```
|_| |_|\___/_/\_\\__,_|___/      \__\___/_/\_\\__|     \___/_/\_\\__|_|  \__,_|\___|\__\___/|_|       |___/\___|_|    \_/ |_|\___\___|
Version: , Server: ${server.address}:49226, Active Profiles: ${spring.active.profiles}
```

**Comment by peterkronenberg** [comment]
The version shows up correctly when running from a jar.  But the server.address and spring.active.profiles does not

**Comment by acanda** [comment]
The plugin does not replace any properties itself. Maven will replace the Maven properties at compile time and Spring Boot will replace the Spring Boot properties when you start the application.

If you use the git-commit-id-plugin then you can have something like `<info>Commit: ${git.commit.id.abbrev}</info>`. Just make sure the git-commit-id-plugin runs before the spring-banner-plugin.
