### ISSUE TITLE
Patch upgrade from 1.3.0 to 1.3.1 requires  Java upgrade

### ISSUE THREAD

**Issue by codefish1** [acanda/spring-banner-plugin#33]
Not sure if you meant to do this but you've upgraded the Java version required from 8 to 11 within a patch upgrade. 

I would of expected this in at least a minor upgrade instead

**Comment by acanda** [comment]
The change from Java 8 to 11 was intentional and you are correct that that should have been at least a minor upgrade. I updated it a while ago and forgot that I did it after the 1.3 release. But since it is already realeased as 1.3.1 there is not much I can do now.

**Comment by codefish1** [comment]
Won't be fixed, so closing issue
